#!/usr/bin/env php
<?php

if (PHP_SAPI !== 'cli') {
    echo 'bin must be run as a CLI application';
    exit(1);
}

define('YII_ENV', 'dev');

// fcgi doesn't have STDIN defined by default
defined('STDIN') or define('STDIN', fopen('php://stdin', 'r'));

define('PROTECTED_DIR', __DIR__ . '/protected');
define('VENDOR_DIR', PROTECTED_DIR . '/vendor');

require __DIR__ . '/protected/vendor/ejsoft/ej-core/bootstrap.php';

$app = (new \ej\base\Boot(['app' => 'console']))
    ->apply('\ej\console\Application');

$exitCode = $app->run();
exit($exitCode);